import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const applications = sqliteTable("applications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  applicantName: text("applicant_name").notNull(),
  applicantPhone: text("applicant_phone").notNull(),
  applicantBirth: text("applicant_birth").notNull(),
  applicantGender: text("applicant_gender").notNull(),
  careerYears: text("career_years").notNull(),
  qualification: text("qualification").notNull().default(""),
  preferredDate: text("preferred_date").notNull(),
  applicationNote: text("application_note").notNull().default(""),
  providerCareType: text("provider_care_type").notNull().default("개인간병"),
  providerSchedule: text("provider_schedule").notNull().default("전일제(24시간)"),
  providerAvailableHours: text("provider_available_hours").notNull().default(""),
  providerRestTerms: text("provider_rest_terms").notNull().default("상호 협의"),
  providerFee: text("provider_fee").notNull().default(""),
  providerFeePeriod: text("provider_fee_period").notNull().default("1일"),
  providerServiceScope: text("provider_service_scope").notNull().default(""),
  providerContractNote: text("provider_contract_note").notNull().default(""),
  providerContractConsent: text("provider_contract_consent").notNull().default("미동의"),
  providerContractVersion: text("provider_contract_version").notNull().default("간병24 제공계약서 v1.0"),
  providerContractSignedAt: text("provider_contract_signed_at").notNull().default(""),
  caregiverHandwriting: text("caregiver_handwriting").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const boardPosts = sqliteTable("board_posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  boardType: text("board_type").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  author: text("author").notNull().default("관리자"),
  attachments: text("attachments").notNull().default("[]"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const careRequests = sqliteTable("care_requests", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  requesterName: text("requester_name").notNull(),
  requesterPhone: text("requester_phone").notNull(),
  patientName: text("patient_name").notNull(),
  patientGender: text("patient_gender").notNull().default(""),
  patientAge: text("patient_age").notNull().default(""),
  patientWeight: text("patient_weight").notNull().default(""),
  diagnosis: text("diagnosis").notNull().default(""),
  patientCondition: text("patient_condition").notNull().default(""),
  precautions: text("precautions").notNull().default(""),
  specialNotes: text("special_notes").notNull().default(""),
  publicConsent: text("public_consent").notNull().default("미동의"),
  building: text("building").notNull(),
  floorName: text("floor_name").notNull().default(""),
  ward: text("ward").notNull(),
  room: text("room").notNull().default(""),
  careType: text("care_type").notNull(),
  startDate: text("start_date").notNull(),
  requestNote: text("request_note").notNull().default(""),
  serviceSchedule: text("service_schedule").notNull().default("전일제(24시간)"),
  serviceStartTime: text("service_start_time").notNull().default(""),
  serviceEndTime: text("service_end_time").notNull().default(""),
  restTime: text("rest_time").notNull().default("상호 협의"),
  holidayTerms: text("holiday_terms").notNull().default("상호 협의"),
  careFee: text("care_fee").notNull().default(""),
  feePeriod: text("fee_period").notNull().default("1일"),
  paymentMethod: text("payment_method").notNull().default("계좌이체"),
  paymentDue: text("payment_due").notNull().default(""),
  serviceScope: text("service_scope").notNull().default(""),
  cancellationTerms: text("cancellation_terms").notNull().default(""),
  contractNote: text("contract_note").notNull().default(""),
  requesterSignature: text("requester_signature").notNull().default(""),
  contractConsent: text("contract_consent").notNull().default("미동의"),
  contractVersion: text("contract_version").notNull().default("간병24 의뢰계약서 v1.0"),
  contractSignedAt: text("contract_signed_at").notNull().default(""),
  desiredGender: text("desired_gender").notNull().default("무관"),
  desiredNationality: text("desired_nationality").notNull().default("무관"),
  desiredExpertise: text("desired_expertise").notNull().default("무관"),
  desiredAge: text("desired_age").notNull().default("무관"),
  desiredPersonality: text("desired_personality").notNull().default("무관"),
  desiredOther: text("desired_other").notNull().default(""),
  status: text("status").notNull().default("requesting"),
  caregiverId: integer("caregiver_id"),
  caregiverName: text("caregiver_name").notNull().default(""),
  caregiverProfile: text("caregiver_profile").notNull().default(""),
  matchedAt: text("matched_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const documentBundles = sqliteTable("document_bundles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  caregiverName: text("caregiver_name").notNull(),
  caregiverPhone: text("caregiver_phone").notNull(),
  bankName: text("bank_name").notNull().default(""),
  accountNumber: text("account_number").notNull().default(""),
  accountHolder: text("account_holder").notNull().default(""),
  documentStatuses: text("document_statuses").notNull(),
  attachments: text("attachments").notNull().default("[]"),
  criminalRequestData: text("criminal_request_data").notNull().default("{}"),
  criminalReviewer: text("criminal_reviewer").notNull().default(""),
  criminalReviewedAt: text("criminal_reviewed_at").notNull().default(""),
  criminalResult: text("criminal_result").notNull().default("확인 대기"),
  evaluation: text("evaluation").notNull(),
  decision: text("decision").notNull(),
  reviewer: text("reviewer").notNull(),
  reviewedAt: text("reviewed_at").notNull(),
  note: text("note").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const privacyConsents = sqliteTable("privacy_consents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  phone: text("phone").notNull(),
  birthDate: text("birth_date").notNull(),
  address: text("address").notNull(),
  retentionPeriod: text("retention_period").notNull(),
  useConsent: text("use_consent").notNull(),
  shareConsent: text("share_consent").notNull(),
  signatureName: text("signature_name").notNull(),
  signedAt: text("signed_at").notNull(),
  caregiverHandwriting: text("caregiver_handwriting").notNull().default(""),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const careContracts = sqliteTable("care_contracts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  contractType: text("contract_type").notNull(),
  employerName: text("employer_name").notNull(),
  employerPhone: text("employer_phone").notNull(),
  employerAddress: text("employer_address").notNull().default(""),
  caregiverName: text("caregiver_name").notNull(),
  caregiverPhone: text("caregiver_phone").notNull(),
  caregiverAddress: text("caregiver_address").notNull().default(""),
  caregiverHandwriting: text("caregiver_handwriting").notNull().default(""),
  patientName: text("patient_name").notNull(),
  workplace: text("workplace").notNull(),
  workStart: text("work_start").notNull(),
  workEnd: text("work_end").notNull(),
  workHours: text("work_hours").notNull(),
  salaryAmount: text("salary_amount").notNull().default(""),
  salaryPeriod: text("salary_period").notNull(),
  fullTimeSalary: text("full_time_salary").notNull().default(""),
  twoShiftSalary: text("two_shift_salary").notNull().default(""),
  threeShiftSalary: text("three_shift_salary").notNull().default(""),
  private24Salary: text("private_24_salary").notNull().default(""),
  privateDay12Salary: text("private_day_12_salary").notNull().default(""),
  privateNight12Salary: text("private_night_12_salary").notNull().default(""),
  privateHourlySalary: text("private_hourly_salary").notNull().default(""),
  payDate: text("pay_date").notNull(),
  bankName: text("bank_name").notNull().default(""),
  bankAccount: text("bank_account").notNull().default(""),
  bankHolder: text("bank_holder").notNull().default(""),
  socialInsurance: text("social_insurance").notNull().default("미가입"),
  retirementPension: text("retirement_pension").notNull().default("미가입"),
  benefitNote: text("benefit_note").notNull().default(""),
  topCount: text("top_count").notNull().default("0"),
  bottomCount: text("bottom_count").notNull().default("0"),
  apronCount: text("apron_count").notNull().default("0"),
  shoesCount: text("shoes_count").notNull().default("0"),
  nameTagCount: text("name_tag_count").notNull().default("0"),
  duties: text("duties").notNull(),
  specialTerms: text("special_terms").notNull().default(""),
  employerSignature: text("employer_signature").notNull(),
  caregiverSignature: text("caregiver_signature").notNull(),
  signedAt: text("signed_at").notNull(),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  confirmedAt: text("confirmed_at"),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
export const submissions = sqliteTable("submissions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  applicantName: text("applicant_name").notNull().default(""),
  applicantPhone: text("applicant_phone").notNull().default(""),
  applicantBirth: text("applicant_birth").notNull().default(""),
  applicantGender: text("applicant_gender").notNull().default(""),
  careerYears: text("career_years").notNull().default(""),
  qualification: text("qualification").notNull().default(""),
  preferredDate: text("preferred_date").notNull().default(""),
  applicationNote: text("application_note").notNull().default(""),
  caregiverName: text("caregiver_name").notNull(),
  caregiverOrg: text("caregiver_org").notNull(),
  caregiverHandwriting: text("caregiver_handwriting").notNull().default(""),
  ward: text("ward").notNull(),
  room: text("room").notNull(),
  patientName: text("patient_name").notNull(),
  workStart: text("work_start").notNull(),
  workEnd: text("work_end").notNull(),
  contractType: text("contract_type").notNull().default("개인간병"),
  feeType: text("fee_type").notNull(),
  feeAmount: text("fee_amount").notNull(),
  feePeriod: text("fee_period").notNull().default("1일"),
  commonFullTimeFee: text("common_full_time_fee").notNull().default(""),
  commonTwoShiftFee: text("common_two_shift_fee").notNull().default(""),
  commonThreeShiftFee: text("common_three_shift_fee").notNull().default(""),
  personalFee: text("personal_fee").notNull().default(""),
  feeNote: text("fee_note").notNull().default(""),
  satisfaction: text("satisfaction").notNull(),
  duties: text("duties").notNull(),
  rules: text("rules").notNull(),
  overall: text("overall").notNull(),
  headNurse: text("head_nurse").notNull(),
  confirmedAt: text("confirmed_at").notNull(),
  status: text("status").notNull().default("saved"),
  sentTargets: text("sent_targets").notNull().default(""),
  completedAt: text("completed_at"),
  createdAt: text("created_at")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});
