"use client";
import { useEffect, useState } from "react";
import { BarChart3, CalendarDays, CheckCircle2, Clock3, HeartHandshake, RefreshCw, ShieldCheck, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import "./matching.css";
import "./security.css";

type RequestRow = { id:number; contractNumber:string; building:string; floorName:string; ward:string; patientGender:string; patientAge?:string; patientWeight?:string; patientName:string; diagnosis:string; patientCondition:string; precautions:string; specialNotes:string; desiredGender:string; desiredNationality:string; desiredExpertise:string; desiredAge:string; desiredPersonality:string; desiredOther:string; status:string };
type Profile = { id:number; applicantName:string; applicantGender:string; careerYears:string; qualification:string; preferredDate:string };
type Stats = Record<"day"|"week"|"month"|"year",{total:number;matched:number}>;
const statusText:Record<string,string>={requesting:"간병의뢰중",matching:"매칭상담중",matched:"매칭완료"};
const emptyStats:Stats={day:{total:0,matched:0},week:{total:0,matched:0},month:{total:0,matched:0},year:{total:0,matched:0}};
const sampleRequests:Record<string,RequestRow[]>={
  "1동":[
    {id:-101,contractNumber:"예시 계약서 01",building:"1동",floorName:"7층",ward:"1병동",patientGender:"여",patientName:"김○○",diagnosis:"고관절 수술 후 회복",patientCondition:"보행 보조 필요",precautions:"낙상 주의",specialNotes:"야간 관찰",desiredGender:"여성",desiredNationality:"무관",desiredExpertise:"재활 간병 경험",desiredAge:"50~60대",desiredPersonality:"차분함",desiredOther:"책임감",status:"requesting"},
    {id:-102,contractNumber:"예시 계약서 02",building:"1동",floorName:"9층",ward:"2병동",patientGender:"남",patientName:"박○○",diagnosis:"뇌졸중 회복기",patientCondition:"부분 도움 필요",precautions:"연하 주의",specialNotes:"체위 변경",desiredGender:"남성",desiredNationality:"한국",desiredExpertise:"뇌신경·재활 경험",desiredAge:"무관",desiredPersonality:"친절함",desiredOther:"",status:"matching"},
  ],
  "2동":[
    {id:-201,contractNumber:"예시 계약서 03",building:"2동",floorName:"8층",ward:"재활병동",patientGender:"여",patientName:"이○○",diagnosis:"척추 수술 후 회복",patientCondition:"이동 보조 필요",precautions:"보조기 착용",specialNotes:"재활 일정 준수",desiredGender:"여성",desiredNationality:"무관",desiredExpertise:"재활 환자 경험",desiredAge:"40~60대",desiredPersonality:"밝고 성실함",desiredOther:"",status:"requesting"},
    {id:-202,contractNumber:"예시 계약서 04",building:"2동",floorName:"9층",ward:"완화의료병동",patientGender:"남",patientName:"최○○",diagnosis:"회복·안정 관리",patientCondition:"상시 관찰 필요",precautions:"감염 예방",specialNotes:"정서 지원",desiredGender:"무관",desiredNationality:"한국",desiredExpertise:"중증환자 경험",desiredAge:"50대 이상",desiredPersonality:"침착함",desiredOther:"야간 가능",status:"matching"},
  ],
};
function CareRequestForm({onSubmit,busy}:{onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean}){
  const [roomStatus,setRoomStatus]=useState("assigned");
  return <form id="patient-care-request" className="request-form" aria-labelledby="patient-care-request-title" onSubmit={onSubmit}><h3 id="patient-care-request-title" tabIndex={-1}>환자·보호자용 간병 의뢰서</h3><div className="request-grid">
    <label>의뢰인 성명<Input name="requesterName" required/></label><label>연락처<Input name="requesterPhone" type="tel" required/></label><label>환자 성명<Input name="patientName" required/></label><label>환자 성별<select name="patientGender" required defaultValue="여"><option>여</option><option>남</option></select></label><label>환자 나이<Input name="patientAge" type="number" min="0" max="120" inputMode="numeric" required placeholder="예: 78"/></label><label>환자 체중 (kg)<Input name="patientWeight" type="number" min="1" max="300" step="0.1" inputMode="decimal" required placeholder="예: 62.5"/></label><label>진단명<Input name="diagnosis" required placeholder="공개 동의한 범위로 기재"/></label><label>환자 상태<Input name="patientCondition" required placeholder="예: 보행 보조 필요"/></label>
    <label>동명<select name="building" required defaultValue="1동"><option>1동</option><option>2동</option></select></label><label>층별명<Input name="floorName" required placeholder="예: 7층"/></label><label>병동명<Input name="ward" required placeholder="예: 1병동"/></label>
    <label className="room-status-field">병실 배정 상태<select name="roomStatus" value={roomStatus} onChange={e=>setRoomStatus(e.target.value)}><option value="assigned">병실 배정 완료</option><option value="emergency_waiting">응급실 대기 중 (병실 미배정·간병인 미지정)</option></select></label>
    <label className={roomStatus==="emergency_waiting"?"room-number-field waiting":"room-number-field"}>병실<Input name="room" disabled={roomStatus==="emergency_waiting"} required={roomStatus==="assigned"} placeholder={roomStatus==="emergency_waiting"?"응급실 대기 중":"예: 701호 (비공개 저장)"}/><small>{roomStatus==="emergency_waiting"?"병실에 올라가기 전 대기 상태로 저장됩니다.":"정확한 병실은 공개 목록에 표시되지 않습니다."}</small></label>
    <label>주의사항<Input name="precautions" placeholder="예: 낙상 주의"/></label><label>특이사항<Input name="specialNotes" placeholder="예: 야간 관찰"/></label><label>간병 구분<select name="careType" required defaultValue="개인간병"><option>개인간병</option><option>공동간병</option></select></label><label>간병 시작일<Input name="startDate" type="date" required/></label><div className="preference-title wide"><b>희망 간병인 조건</b><span>무관을 선택하거나 원하는 조건을 공개할 수 있습니다.</span></div><label>희망 성별<select name="desiredGender" defaultValue="무관"><option>무관</option><option>여성</option><option>남성</option></select></label><label>희망 국적<select name="desiredNationality" defaultValue="무관"><option>무관</option><option>한국</option><option>중국</option><option>기타</option></select></label><label>희망 나이대<select name="desiredAge" defaultValue="무관"><option>무관</option><option>30대</option><option>40대</option><option>50대</option><option>60대</option><option>70대</option></select></label><label className="wide">희망 전문성<Input name="desiredExpertise" defaultValue="무관"/></label><label className="wide">희망 성격<Input name="desiredPersonality" defaultValue="무관"/></label><label className="wide">기타 공개조건<Input name="desiredOther"/></label><label className="wide">요청사항<Input name="requestNote" placeholder="비공개 저장"/></label><label className="public-consent wide"><input type="checkbox" name="publicConsent" value="동의" required/><span><b>민감정보 공개 동의</b> 진단명·환자상태·주의사항·특이사항의 공개에 동의합니다. 환자 이름은 자동으로 가림 표시됩니다.</span></label>
    <fieldset className="care-request-contract wide">
      <legend>돌봄서비스(간병) 의뢰계약서</legend>
      <div className="contract-source-note"><ShieldCheck/><span><b>앱용 자체 계약서</b> 서울형 간병인 표준계약서와 보건복지부 표준계약 항목을 참고해 병원 개인간병 의뢰용으로 구성했습니다. 병원 공식 서식은 아닙니다.</span></div>
      <div className="contract-grid">
        <label>급여기준<select name="serviceSchedule" required defaultValue="전일제(24시간)"><option>전일제(24시간)</option><option>주간제(12시간)</option><option>야간제(12시간)</option><option>시간제(12시간 미만)</option></select></label>
        <label>서비스 시작시간<Input name="serviceStartTime" type="time"/></label><label>서비스 종료시간<Input name="serviceEndTime" type="time"/></label>
        <label>휴게시간<Input name="restTime" required defaultValue="상호 협의"/></label><label>휴일·휴무<Input name="holidayTerms" required defaultValue="상호 협의"/></label>
        <label>협의 간병비<Input name="careFee" required inputMode="numeric" placeholder="예: 150,000원"/></label><label>금액 단위<select name="feePeriod" required defaultValue="1일"><option>1시간</option><option>1일</option><option>1주</option><option>1개월</option><option>총 계약기간</option></select></label>
        <label>지급 방법<select name="paymentMethod" required defaultValue="계좌이체"><option>계좌이체</option><option>현금</option><option>기타</option></select></label><label>지급 시기<Input name="paymentDue" required placeholder="예: 매일 근무 종료 후"/></label>
        <label className="wide">서비스 범위<Input name="serviceScope" required defaultValue="식사·위생·배설·이동·체위변경·환경관리·정서지원·상태 관찰 및 간호사 보고"/></label>
        <label className="wide">변경·취소 조건<Input name="cancellationTerms" required defaultValue="근무 시작 전 변경·취소는 상대방에게 즉시 알리고, 발생 비용은 사전 협의한 내용에 따름"/></label>
        <label className="wide">특약사항<Input name="contractNote" placeholder="추가로 합의한 내용이 있을 때 기재"/></label>
      </div>
      <div className="contract-clauses"><b>계약 당사자 확인사항</b><ol><li>간병인은 위 서비스 범위와 병동 안전·감염관리 지침을 준수하고, 환자 상태 변화는 간호사실에 즉시 알립니다.</li><li>의료인이 아닌 간병인은 투약·처치 등 의료행위를 임의로 하지 않습니다.</li><li>의뢰인은 환자 상태와 주의사항을 정확히 알리고, 간병비와 추가 비용은 사전에 서면으로 합의합니다.</li><li>양측은 환자와 간병인의 개인정보를 보호하며, 계약 변경·종료 사항은 서로 확인할 수 있게 기록합니다.</li></ol></div>
      <label className="signature-field">의뢰인 전자서명<Input name="requesterSignature" required placeholder="의뢰인 성명을 직접 입력하면 전자서명으로 저장됩니다."/></label>
      <label className="contract-consent"><input type="checkbox" name="contractConsent" value="동의" required/><span><b>계약 내용 동의</b> 위 서비스 내용·간병비·지급방법·변경 및 취소 조건을 확인하고 계약서 생성에 동의합니다.</span></label>
    </fieldset>
  </div><Button type="submit" disabled={busy}>의뢰서·계약서 저장 및 공개</Button></form>
}

export default function LiveMatching({requestSequence=0}:{requestSequence?:number}){
  const [requests,setRequests]=useState<RequestRow[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[stats,setStats]=useState<Stats>(emptyStats),[formOpen,setFormOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[updated,setUpdated]=useState(""),[flashId,setFlashId]=useState<number|null>(null),[lastContract,setLastContract]=useState<string>("");
  async function load(){try{const r=await fetch("/api/care-requests",{cache:"no-store"}),j=await r.json();if(r.ok){setRequests(j.requests||[]);setProfiles(j.profiles||[]);setStats(j.stats||emptyStats);setUpdated(new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}));}}catch{}}
  useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(requestSequence>0)setFormOpen(true)},[requestSequence]);
  useEffect(()=>{if(!formOpen)return;const frame=window.requestAnimationFrame(()=>{document.getElementById("patient-care-request")?.scrollIntoView({behavior:"instant",block:"start"});document.getElementById("patient-care-request-title")?.focus({preventScroll:true})});return()=>window.cancelAnimationFrame(frame)},[formOpen,requestSequence]);
  useEffect(()=>{if(!flashId)return;const timer=window.setTimeout(()=>{const row=Array.from(document.querySelectorAll<HTMLElement>(".care-table-item")).find(item=>item.querySelector(".care-table-row>strong")?.textContent===String(flashId));if(!row)return;row.classList.add("just-applied");const badge=row.querySelector<HTMLElement>(".match-status");if(badge){badge.dataset.originalText=badge.textContent||"매칭상담중";badge.textContent="신청완료 · 매칭상담중"}},60);return()=>{window.clearTimeout(timer);document.querySelectorAll<HTMLElement>(".care-table-item.just-applied").forEach(item=>{item.classList.remove("just-applied");const badge=item.querySelector<HTMLElement>(".match-status");if(badge?.dataset.originalText)badge.textContent=badge.dataset.originalText})}},[flashId,requests]);
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,body=Object.fromEntries(new FormData(form));try{const r=await fetch("/api/care-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error);form.reset();setFormOpen(false);setLastContract(j.contract?.number||"");setMessage(`간병 의뢰계약서 ${j.contract?.number||""} 자동생성·저장·공개가 완료되었습니다.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"저장하지 못했습니다.")}finally{setBusy(false)}}
  async function action(id:number,action:string,caregiverId?:number){setBusy(true);setMessage("");try{const r=await fetch("/api/care-requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action,caregiverId})}),j=await r.json();if(!r.ok)throw Error(j.error);if(action==="apply"){setFlashId(id);setLastContract(j.contract?.number||"")}setMessage(action==="apply"?`간병 신청과 매칭이 완료되었습니다. 계약번호 ${j.contract?.number||""}`:"매칭이 완료되어 실시간 의뢰 목록에서 삭제되었습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:"처리하지 못했습니다.")}finally{setBusy(false)}}
  function buildingQueue(building:string){const rows=requests.filter(x=>x.building===building);return <section className={`building-queue ${building==="1동"?"building-one":"building-two"}`} key={building}><header><div><strong>{building}</strong><span>실시간 간병의뢰</span></div><div><b>간병의뢰 {rows.filter(x=>x.status==="requesting").length}</b><b>매칭상담 {rows.filter(x=>x.status==="matching").length}</b></div></header><div className="public-columns"><b>번호</b><b>동명</b><b>층별명</b><b>병동명</b><b>상태</b></div><div className="request-list live-flow">{rows.length===0?<div className="no-requests"><BarChart3/><b>{building}에 공개 중인 의뢰가 없습니다.</b><span>새 의뢰가 등록되면 이곳에 표시됩니다.</span></div>:rows.map(x=><article key={x.id} className={`request-card ${x.status}`}><div className="public-request-row"><strong>{x.id}</strong><span>{x.building}</span><span>{x.floorName}</span><span>{x.ward}</span><span className={`match-status ${x.status}`}>{statusText[x.status]||x.status}</span></div><div className="care-preferences"><b>희망 간병인</b><span>성별 <strong>{x.desiredGender}</strong></span><span>국적 <strong>{x.desiredNationality}</strong></span><span>나이 <strong>{x.desiredAge}</strong></span><span>전문성 <strong>{x.desiredExpertise}</strong></span><span>성격 <strong>{x.desiredPersonality}</strong></span>{x.desiredOther&&<span>기타 <strong>{x.desiredOther}</strong></span>}</div>{x.status==="requesting"?<div className="profile-apply"><select id={`profile-${x.id}`} defaultValue=""><option value="">저장된 간병인 프로필 선택</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.applicantName} · {p.applicantGender} · 경력 {p.careerYears}{p.qualification?` · ${p.qualification}`:""}</option>)}</select><Button type="button" disabled={busy||profiles.length===0} onClick={()=>{const el=document.getElementById(`profile-${x.id}`) as HTMLSelectElement;action(x.id,"apply",Number(el.value))}}>이 프로필로 신청</Button></div>:<div className="selected-profile consultation"><UserRoundCheck/><span><b>매칭 상담 진행 중</b><small>세부정보는 관계자만 확인합니다.</small></span><Button type="button" disabled={busy} onClick={()=>action(x.id,"complete")}>매칭 완료 처리</Button></div>}</article>)}</div></section>}
  function buildingTable(building:string){const realRows=requests.filter(x=>x.building===building),rows=realRows.length?realRows:sampleRequests[building];return <section className={`building-queue wide-building-table ${building==="1동"?"building-one":"building-two"}`} key={building}><header><div><strong>{building}</strong><span>실시간 간병의뢰</span></div><div><b>간병의뢰 {realRows.filter(x=>x.status==="requesting").length}</b><b>매칭상담 {realRows.filter(x=>x.status==="matching").length}</b></div></header>{!realRows.length&&<p className="sample-notice">실제 의뢰가 등록되기 전 표시되는 예시 2건입니다.</p>}<div className="wide-table-scroll"><div className="care-table-head"><b>번호</b><b>동명</b><b>층별명</b><b>병동명</b><b>환자 성별</b><b>이름</b><b>진단명</b><b>상태</b><b>주의사항</b><b>특이사항</b><b>원하는 간병인 조건</b><b>진행상태</b></div>{rows.map(x=>{const sample=x.id<0,condition=`성별 ${x.desiredGender} · 국적 ${x.desiredNationality} · 나이 ${x.desiredAge} · 전문성 ${x.desiredExpertise} · 성격 ${x.desiredPersonality}${x.desiredOther?` · 기타 ${x.desiredOther}`:""}`;return <article className={`care-table-item ${x.status}`} key={x.id}><div className="care-table-row"><strong>{sample?"예시":x.id}</strong><span>{x.building}</span><span>{x.floorName}</span><span>{x.ward}</span><span>{x.patientGender}</span><span>{x.patientName}</span><span>{x.diagnosis}</span><span>{x.patientCondition}</span><span>{x.precautions||"-"}</span><span>{x.specialNotes||"-"}</span><span className="wanted-condition">{condition}</span><span className={`match-status ${x.status}`}>{statusText[x.status]}</span></div>{sample?<div className="sample-action">예시 자료</div>:x.status==="requesting"?<div className="profile-apply"><select id={`profile-${x.id}`} defaultValue=""><option value="">저장된 간병인 프로필 선택</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.applicantName} · {p.applicantGender} · 경력 {p.careerYears}{p.qualification?` · ${p.qualification}`:""}</option>)}</select><Button type="button" disabled={busy||profiles.length===0} onClick={()=>{const el=document.getElementById(`profile-${x.id}`) as HTMLSelectElement;action(x.id,"apply",Number(el.value))}}>이 프로필로 신청</Button></div>:<div className="selected-profile consultation"><UserRoundCheck/><span><b>매칭 상담 진행 중</b><small>세부정보는 관계자만 확인합니다.</small></span><Button type="button" disabled={busy} onClick={()=>action(x.id,"complete")}>매칭 완료 처리</Button></div>}</article>})}</div></section>}
  return <section id="live-matching" className="live-matching">
    <header><div><p>실시간 간병 연결</p><h2>간병 의뢰·매칭 현황</h2><span><i></i>{updated?`${updated} 기준 · 5초마다 자동 갱신`:"현황 불러오는 중"}</span></div><div><Button type="button" variant="outline" onClick={load}><RefreshCw/>새로고침</Button><Button type="button" onClick={()=>setFormOpen(!formOpen)}><HeartHandshake/>{formOpen?"작성 닫기":"간병 의뢰하기"}</Button></div></header>
    <div className="contract-flow-banner"><CheckCircle2/><span><b>의뢰서 저장 → 의뢰계약서 자동생성·공개 → 간병인 신청 즉시 매칭완료</b><small>연락처·정확한 병실 등 개인정보는 관계자에게만 비공개로 저장됩니다.</small></span></div>
    <div className="matching-security"><ShieldCheck/><div><b>동의 범위 안에서 공개</b><span>환자·보호자가 동의한 상태·주의사항과 희망 간병인 조건을 공개합니다. 이름은 가림 처리하며 연락처·정확한 병실·간병비는 공개하지 않습니다.</span></div></div>
    {formOpen&&<CareRequestForm onSubmit={create} busy={busy}/>}
    {message&&<p className="matching-message">{message}</p>}{lastContract&&<div className="auto-contract"><CheckCircle2/><div><b>간병 의뢰계약서 자동생성</b><span>계약번호 {lastContract} · 개인정보 비공개 저장 · 공개 동의 항목만 공개</span></div></div>}
    <div className="matching-workspace">
      <div className="matching-queue">
        <div className="today-queue-head"><div><span>오늘 접수</span><strong>{stats.day.total}건</strong></div><p><i></i>간병인이 새 의뢰를 확인하고 저장된 프로필로 바로 신청할 수 있습니다.</p></div>
        <div className="status-guide"><span className="requesting"><Clock3/>전체 간병의뢰 {requests.filter(x=>x.status==="requesting").length}</span><span className="matching"><UserRoundCheck/>전체 매칭상담 {requests.filter(x=>x.status==="matching").length}</span><span className="matched"><CheckCircle2/>오늘 매칭완료 {stats.day.matched}</span></div>
        <div className="building-queues">{["1동","2동"].map(buildingTable)}</div>
      </div>
      <aside className="matching-summary"><header><BarChart3/><div><b>누적 현황</b><span>실시간 자동 집계</span></div></header><div className="matching-stats">{[["일",stats.day],["주",stats.week],["월",stats.month],["년",stats.year]].map(([label,value]:any)=><article key={label}><CalendarDays/><span><b>{label} 누적 {value.total}건</b><small>매칭완료 {value.matched}건</small></span></article>)}</div></aside>
    </div>
  </section>
}
