import {createClient} from '@libsql/client';
import {mkdir,writeFile} from 'node:fs/promises';
import {newToken,tokenHash} from '../lib/auth-crypto.mjs';
const db=createClient({url:process.env.CARE24_DATABASE_URL});
if((await db.execute("SELECT id FROM auth_users WHERE role='admin'")).rows.length)throw new Error('Admin already exists. Setup disabled.');
const token=newToken();
await db.execute({sql:'INSERT INTO auth_bootstrap(id,token_hash,expires_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET token_hash=excluded.token_hash,expires_at=excluded.expires_at',args:[tokenHash(token),Date.now()+3600000]});
await mkdir('.private',{recursive:true,mode:0o700});
await writeFile('.private/admin-setup-url.txt',`${process.env.CARE24_ORIGIN}/setup#${token}`,{mode:0o600});
console.log('One-hour setup link saved in .private/admin-setup-url.txt. Do not publish this file.');
db.close();
