plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.or.care24.app'
    compileSdk 35

    defaultConfig {
        applicationId 'kr.or.care24.app'
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName '1.1.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {}
