CREATE TABLE `submissions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`caregiver_name` text NOT NULL,
	`caregiver_org` text NOT NULL,
	`ward` text NOT NULL,
	`room` text NOT NULL,
	`patient_name` text NOT NULL,
	`work_start` text NOT NULL,
	`work_end` text NOT NULL,
	`fee_type` text NOT NULL,
	`fee_amount` text NOT NULL,
	`fee_note` text DEFAULT '' NOT NULL,
	`satisfaction` text NOT NULL,
	`duties` text NOT NULL,
	`rules` text NOT NULL,
	`overall` text NOT NULL,
	`head_nurse` text NOT NULL,
	`confirmed_at` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
