CREATE TABLE `care_contracts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`contract_type` text NOT NULL,
	`employer_name` text NOT NULL,
	`employer_phone` text NOT NULL,
	`employer_address` text DEFAULT '' NOT NULL,
	`caregiver_name` text NOT NULL,
	`caregiver_phone` text NOT NULL,
	`caregiver_address` text DEFAULT '' NOT NULL,
	`patient_name` text NOT NULL,
	`workplace` text NOT NULL,
	`work_start` text NOT NULL,
	`work_end` text NOT NULL,
	`work_hours` text NOT NULL,
	`salary_amount` text DEFAULT '' NOT NULL,
	`salary_period` text NOT NULL,
	`full_time_salary` text DEFAULT '' NOT NULL,
	`two_shift_salary` text DEFAULT '' NOT NULL,
	`three_shift_salary` text DEFAULT '' NOT NULL,
	`pay_date` text NOT NULL,
	`duties` text NOT NULL,
	`special_terms` text DEFAULT '' NOT NULL,
	`employer_signature` text NOT NULL,
	`caregiver_signature` text NOT NULL,
	`signed_at` text NOT NULL,
	`status` text DEFAULT 'saved' NOT NULL,
	`sent_targets` text DEFAULT '' NOT NULL,
	`confirmed_at` text,
	`completed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
